---

# Install base packages, common to all servers
- name: Install common packages
  apt: name="{{ item }}" state=present
  sudo: yes
  with_items:
    - build-essential
    - python-pip
    - python-dev
    - python-setuptools
    - python-psycopg2
    - libxml2-dev
    - libxslt1-dev
    - git
    - libpq-dev
    - curl
    - htop
    - tmpreaper
    - mailutils
    - ntp
    - nodejs
    - at
    - screen
    - gettext
    - python-software-properties
    - mosh
    - libjpeg-dev
    - libfreetype6-dev
    - gradle
    - ranger  # cmdline file browser
    - libffi-dev  # Required for installing github3py
    - libssl-dev  # Required for pip setup tools
    - tmux
    - unzip
    - iotop
    - ncdu # 'du' improved
    - tig

- name: Install pip packages
  pip: name="{{ item }}"
  sudo: yes
  with_items:
    - virtualenv
    - sh
    - httplib2

- name: Install virtualenv-clone
  sudo: yes
  pip:
    name: virtualenv-clone
    version: 0.2.6
